export 'package:smarttolls/views/vehicles/add_vehicles_view.dart';
export 'package:smarttolls/views/home/home_view.dart';
export 'package:smarttolls/views/login/login_view.dart';
export 'package:smarttolls/views/navBar/nav_bar_view.dart';
export 'package:smarttolls/views/signup/signup_view.dart';
export 'package:smarttolls/views/signup/signup_step_two_view.dart';
export 'package:smarttolls/views/vehicles/vehicles_view.dart';
export 'package:smarttolls/views/welcome/welcome_view.dart';
export 'package:smarttolls/views/wallet/wallet_view.dart';